### PR TITLE
Move GET to POST of request method

### PR DESCRIPTION
**Pull request by ryuneeee**
Hello,

GET method is exposed username, query in url. Logging in auth server, logs can have username, password and some access logs. That is vulnerable in backend.

**Examples**

|Method|Logs|
|----------|------|
|GET|54.238.115.29 - - [11/May/2015 18:36:40] "GET /auth/user?username=administrator&password=LodgRhs1vx6c HTTP/1.0" 200 5|
|POST|54.238.115.29 - - [11/May/2015 18:36:40] "POST /auth/user HTTP/1.0" 200 5|

### CODE REVIEW

**Comment by hairyhum** [comment]
Related to #7 
I think there should be option to use `GET` or `POST`, for backwards compatibility.

**Comment by michaelklishin** [comment]
@hairyhum sounds good. We should use POST by default (and thus this is for `3.7.0`), though.

**Comment by hairyhum** [comment]
@ryuneeee can you update this PR to support backwards compatible `GET` with configuration key?

**Comment by michaelklishin** [comment]
This no longer merges cleanly.

**Comment by michaelklishin** [comment]
@ryuneeee hi, can you please address the comment above from @hairyhum so that it can go into a `3.6.x` release and not `3.7.0`? If not, can you at least rebase this PR so that it merges cleanly? Thank you.

**Comment by ryuneeee** [comment]
@hairyhum I can't. I'm not learned erlang language. Whatever do you want if you find better solution :)

**Comment by hairyhum** [comment]
Closed in favor of #30

**Pull request closed without merging**
