### PR TITLE
Dockerize django example

### PR DESCRIPTION
**Pull request by d21d3q**
I'm finding docker-compose a convenient way to quickly run project/tool and play around with it.

This PR allows for running whole stack with one line and observe how auth calls are being made. It can also run client ([nodered](https://nodered.org/)) as option.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@d21d3q Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-http&pullRequestId=93)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-http&pullRequestId=93) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@d21d3q Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-http&pullRequestId=93)!

**Comment by michaelklishin** [comment]
Merged with some minor example config and README wording changes. Thank you!

**Comment by michaelklishin** [comment]
Backported to `v3.7.x`.

**Pull request merged**
