### PR TITLE
Added a missing type declaration.

### PR DESCRIPTION
**Pull request by xneg**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@xneg Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-http&pullRequestId=70)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-http&pullRequestId=70) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@xneg Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-auth-backend-http&pullRequestId=70)!

**Comment by michaelklishin** [comment]
Thank you!

**Comment by xneg** [comment]
Added only for compilation purposes 🙂

**Pull request merged**
